# - Find BERKELYDB
# Find the native BERKELYDB includes and library
#
#   BERKELYDB_FOUND       - True if BERKELYDB found.
#   BERKELYDB_INCLUDE_DIR - where to find includes
#   BERKELYDB_LIBRARIES   - List of libraries when using BERKELYDB.
#

IF( BERKELYDB_INCLUDE_DIR )
    # Already in cache, be silent
    SET( BERKELYDB_FIND_QUIETLY TRUE )
ENDIF( BERKELYDB_INCLUDE_DIR )

FIND_PATH( BERKELYDB_INCLUDE_DIR "db.h" HINTS "${BERKELYDB_ROOT}/include")

FIND_LIBRARY( BERKELYDB_LIBRARY libdb HINTS "${BERKELYDB_ROOT}/lib")
SET(BERKELYDB_LIBRARIES ${BERKELYDB_LIBRARY})

# handle the QUIETLY and REQUIRED arguments and set BERKELYDB_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE( "FindPackageHandleStandardArgs" )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( "BERKELYDB" DEFAULT_MSG BERKELYDB_INCLUDE_DIR BERKELYDB_LIBRARY )

MARK_AS_ADVANCED( BERKELYDB_INCLUDE_DIR BERKELYDB_LIBRARIES )